import { FileSystem, JsonFile, JsonObject } from '@rushstack/node-core-library';
import Console from '../providers/console';
import { Colorize } from '@rushstack/terminal';
import { RushConstants } from '@rushstack/rush-sdk';
import { RushNameConstants } from '../constants/paths';
import { satisfies } from 'semver';

export const updateSubspaceAlternativeVersions = (
  availableVersions: string[],
  versionsToUpdate: string[]
): string[] => {
  const newVersions: string[] = [...availableVersions, ...versionsToUpdate];

  // Remove duplicates
  const validVersions: string[] = newVersions.filter((version, index, currValidVersions) => {
    return currValidVersions.some((validVersion) => satisfies(version, validVersion));
  });

  return validVersions;
};

const mergeSubspaceCommonVersionsFiles = (
  sourceSubspaceFolderPath: string,
  targetSubspaceFolderPath: string
): void => {
  const sourceCommonVersionsFilePath: string = `${sourceSubspaceFolderPath}/${RushConstants.commonVersionsFilename}`;
  const targetCommonVersionsFilePath: string = `${targetSubspaceFolderPath}/${RushConstants.commonVersionsFilename}`;

  const sourceCommonVersions: JsonObject = JsonFile.load(sourceCommonVersionsFilePath);
  if (FileSystem.exists(targetCommonVersionsFilePath)) {
    const targetCommonVersions: JsonObject = JsonFile.load(targetCommonVersionsFilePath);

    for (const [dependency, version] of Object.entries<string>(sourceCommonVersions.preferredVersions)) {
      const targetPreferredVersion: string | undefined = targetCommonVersions.preferredVersions[dependency];
      if (targetPreferredVersion) {
        Console.warn(
          `There are conflicting values for ${Colorize.bold(dependency)} in the ${Colorize.bold(
            RushConstants.commonVersionsFilename
          )} file's preferredVersions: ${Colorize.bold(version)} and ${Colorize.bold(
            targetPreferredVersion
          )}. Please fix.`
        );
      } else {
        targetCommonVersions.preferredVersions[dependency] = version;
      }
    }

    for (const [dependency, versions] of Object.entries<string[]>(
      sourceCommonVersions.allowedAlternativeVersions
    )) {
      targetCommonVersions.allowedAlternativeVersions[dependency] = updateSubspaceAlternativeVersions(
        targetCommonVersions.allowedAlternativeVersions[dependency] || [],
        versions
      );
    }

    Console.debug(
      `Merging ${Colorize.bold(sourceCommonVersionsFilePath)} with ${Colorize.bold(
        targetCommonVersionsFilePath
      )}...`
    );
    JsonFile.save(targetCommonVersions, targetCommonVersionsFilePath, {
      updateExistingFile: true
    });
  } else {
    Console.debug(
      `Copying ${Colorize.bold(sourceCommonVersionsFilePath)} into ${Colorize.bold(
        targetCommonVersionsFilePath
      )}...`
    );

    FileSystem.copyFile({
      sourcePath: sourceCommonVersionsFilePath,
      destinationPath: targetCommonVersionsFilePath
    });
  }
};

/**
 * @deprecated We no longer need to copy the repoState file, since it should be generated by rush.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const copySubspaceRepoStateFile = (
  sourceSubspaceFolderPath: string,
  targetSubspaceFolderPath: string
): void => {
  const sourceRepoStateFilePath: string = `${sourceSubspaceFolderPath}/${RushConstants.repoStateFilename}`;
  const targetRepoStateFilePath: string = `${targetSubspaceFolderPath}/${RushConstants.repoStateFilename}`;
  if (!FileSystem.exists(targetRepoStateFilePath)) {
    Console.debug(
      `Copying ${Colorize.bold(sourceRepoStateFilePath)} into ${Colorize.bold(targetRepoStateFilePath)}...`
    );

    FileSystem.copyFile({
      sourcePath: sourceRepoStateFilePath,
      destinationPath: targetRepoStateFilePath
    });
  }
};

const mergeSubspacePnpmFiles = (sourceSubspaceFolderPath: string, targetSubspaceFolderPath: string): void => {
  const sourcePnpmFilePath: string = `${sourceSubspaceFolderPath}/${RushNameConstants.PnpmSubspaceFileName}`;
  const targetPnpmFilePath: string = `${targetSubspaceFolderPath}/${RushNameConstants.PnpmSubspaceFileName}`;

  if (FileSystem.exists(sourcePnpmFilePath)) {
    if (FileSystem.exists(targetPnpmFilePath)) {
      const tempPnpmSubspaceFileName: string = `.pnpmfile-subspace-temp_${new Date().getTime()}.cjs`;
      const targetPnpmTempFilePath: string = `${targetSubspaceFolderPath}/${tempPnpmSubspaceFileName}`;
      Console.debug(
        `Duplicating temporary ${Colorize.bold(sourcePnpmFilePath)} into ${Colorize.bold(
          targetPnpmFilePath
        )}...`
      );

      FileSystem.copyFile({
        sourcePath: sourcePnpmFilePath,
        destinationPath: targetPnpmTempFilePath
      });

      Console.warn(
        `There are now two ${Colorize.bold(RushNameConstants.PnpmSubspaceFileName)}. (${Colorize.bold(
          RushNameConstants.PnpmSubspaceFileName
        )} and .${Colorize.bold(
          tempPnpmSubspaceFileName
        )}). Please reconcile them into a singular ${Colorize.bold(
          RushNameConstants.PnpmSubspaceFileName
        )} manually.`
      );
    } else {
      Console.debug(
        `Copying ${Colorize.bold(sourcePnpmFilePath)} into ${Colorize.bold(targetPnpmFilePath)}...`
      );
      FileSystem.copyFile({
        sourcePath: sourcePnpmFilePath,
        destinationPath: targetPnpmFilePath
      });
    }
  }
};

const copySubspaceNpmRcFile = (sourceSubspaceFolderPath: string, targetSubspaceFolderPath: string): void => {
  const sourceNpmRcFilePath: string = `${sourceSubspaceFolderPath}/${RushNameConstants.NpmRcFileName}`;
  const targetNpmRcFilePath: string = `${targetSubspaceFolderPath}/${RushNameConstants.NpmRcFileName}`;

  if (FileSystem.exists(sourceNpmRcFilePath)) {
    Console.debug(
      `Copying ${Colorize.bold(sourceNpmRcFilePath)} into ${Colorize.bold(targetNpmRcFilePath)}...`
    );
    FileSystem.copyFile({
      sourcePath: sourceNpmRcFilePath,
      destinationPath: targetNpmRcFilePath
    });
  }
};

export const updateSubspace = async (
  sourceSubspaceConfigurationFolderPath: string,
  targetSubspaceConfigurationFolderPath: string
): Promise<void> => {
  copySubspaceNpmRcFile(sourceSubspaceConfigurationFolderPath, targetSubspaceConfigurationFolderPath);
  mergeSubspaceCommonVersionsFiles(
    sourceSubspaceConfigurationFolderPath,
    targetSubspaceConfigurationFolderPath
  );
  // copySubspaceRepoStateFile(sourceSubspaceConfigurationFolderPath, targetSubspaceConfigurationFolderPath);
  mergeSubspacePnpmFiles(sourceSubspaceConfigurationFolderPath, targetSubspaceConfigurationFolderPath);
};
